version: "3.8"

services:
  springboot-app:
    build: .
    image: doceh/springboot-lib-app-aws
    container_name: library-app-container-aws
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - spring-net

networks:
  spring-net:
