---
sonarqube_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip"
sonarqube_archive: "sonarqube-{{ sonarqube_version }}.zip"
sonarqube_extract_dir: "/opt/sonarqube-{{ sonarqube_version }}"

