plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1
filters:
  instance-state-name: running
  tag:Name:
    - sonar
    - nexus
keyed_groups:
  - prefix: tag
    key: tags.Name
hostnames:
  - public_ip_address
compose:
  ansible_host: public_ip_address
