plugin: aws_ec2
regions:
  - ap-south-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.AnsibleGroup
    prefix: tag
    separator: "_"
hostnames:
  - public-ip-address
compose:
  ansible_host: public-ip-address
cache: false