plugin: aws_ec2
regions:
  - ap-south-1
filters:
  instance-state-name: running
  tag:Environment: dev   

keyed_groups:
  - key: tags.Name
    prefix: tag

hostnames:
  - instance-id

compose:
  ansible_host: instance-id
