plugin: aws_ec2
regions:
  - ap-south-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: tag_Name
    separator: "_"
hostnames:
  - instance-id  # Since SSM uses instance ID
compose:
  ansible_host: instance-id
